INSERT INTO parking_slots (id, type, price_per_day, location, max_vehicles, features, status, image_path) VALUES
(1, 'Valet Parking', 350.00, 'Near Entrance', 1, 'Valet Service, 24/7 Access, Secure, Fast Drop-off', 'available', 'images/parking1.jpg'),
(2, 'Self-Parking', 200.00, 'Valet Zone', 1, 'Self Service, 24/7 Access, Secure', 'available', 'images/parking2.jpg'),
(3, 'Underground Parking', 250.00, 'Lobby', 1, 'CCTV, Climate Control, 24/7 Access, Secure', 'available', 'images/parking3.jpg'),
(4, 'EV Charging Parking', 300.00, 'Drop-off', 1, 'EV Charging, Fast Charge, 24/7 Access', 'available', 'images/parking4.jpg'),
(5, 'VIP Reserved Parking', 500.00, 'VIP Valet', 1, 'VIP Access, Premium Security, Reserved', 'available', 'images/parking5.jpg'),
(6, 'Two-Wheeler Parking', 100.00, 'Main Gate', 1, 'Motorcycle, Scooter, 24/7 Access', 'available', 'images/parking6.jpg'),
(7, 'Covered Parking', 180.00, 'Self-Park A', 1, 'Weather Protection, CCTV, 24/7 Access', 'available', 'images/parking7.jpg'),
(8, 'Outdoor Guest Parking', 120.00, 'Self-Park B', 1, 'Open Air, General Access, 24/7', 'available', 'images/parking8.jpg'),
(9, 'Long-Term Parking', 150.00, 'Self-Park C', 1, 'Long-Term, Secure, 24/7 Access', 'available', 'images/parking9.jpg'),
(10, 'Staff Parking', 0.00, 'Self-Park D', 1, 'Staff Only, Reserved, Secure', 'available', 'images/parking10.jpg'),
(11, 'Valet Parking', 350.00, 'Covered', 1, 'Valet Service, 24/7 Access, Secure, Fast Drop-off', 'available', 'images/parking11.jpg'),
(12, 'Self-Parking', 200.00, 'Open Air', 1, 'Self Service, 24/7 Access, Secure', 'available', 'images/parking12.jpg'),
(13, 'Underground Parking', 250.00, 'EV Charger', 1, 'CCTV, Climate Control, 24/7 Access, Secure', 'available', 'images/parking13.jpg'),
(14, 'EV Charging Parking', 300.00, 'Long-Term', 1, 'EV Charging, Fast Charge, 24/7 Access', 'available', 'images/parking14.jpg'),
(15, 'VIP Reserved Parking', 500.00, 'VIP Zone', 1, 'VIP Access, Premium Security, Reserved', 'available', 'images/parking15.jpg'),
(16, 'Two-Wheeler Parking', 100.00, 'Basement', 1, 'Motorcycle, Scooter, 24/7 Access', 'available', 'images/parking16.jpg'),
(17, 'Covered Parking', 180.00, 'Outdoor', 1, 'Weather Protection, CCTV, 24/7 Access', 'available', 'images/parking17.jpg'),
(18, 'Outdoor Guest Parking', 120.00, 'Premium', 1, 'Open Air, General Access, 24/7', 'available', 'images/parking18.jpg'),
(19, 'Long-Term Parking', 150.00, 'Standard', 1, 'Long-Term, Secure, 24/7 Access', 'available', 'images/parking19.jpg'),
(20, 'Staff Parking', 0.00, 'Family', 1, 'Staff Only, Reserved, Secure', 'available', 'images/parking20.jpg'),
(21, 'Valet Parking', 350.00, 'Near Entrance 2', 1, 'Valet Service, 24/7 Access, Secure, Fast Drop-off', 'available', 'images/parking5.jpg'),
(22, 'Self-Parking', 200.00, 'Valet Zone 2', 1, 'Self Service, 24/7 Access, Secure', 'available', 'images/parking9.jpg'),
(23, 'Underground Parking', 250.00, 'Lobby 2', 1, 'CCTV, Climate Control, 24/7 Access, Secure', 'available', 'images/parking12.jpg'),
(24, 'EV Charging Parking', 300.00, 'Drop-off 2', 1, 'EV Charging, Fast Charge, 24/7 Access', 'available', 'images/parking15.jpg'),
(25, 'VIP Reserved Parking', 500.00, 'VIP Valet 2', 1, 'VIP Access, Premium Security, Reserved', 'available', 'images/parking18.jpg'),
(26, 'Two-Wheeler Parking', 100.00, 'Main Gate 2', 1, 'Motorcycle, Scooter, 24/7 Access', 'available', 'images/parking1.jpg'),
(27, 'Covered Parking', 180.00, 'Self-Park E', 1, 'Weather Protection, CCTV, 24/7 Access', 'available', 'images/parking7.jpg'),
(28, 'Outdoor Guest Parking', 120.00, 'Self-Park F', 1, 'Open Air, General Access, 24/7', 'available', 'images/parking3.jpg'),
(29, 'Long-Term Parking', 150.00, 'Self-Park G', 1, 'Long-Term, Secure, 24/7 Access', 'available', 'images/parking9.jpg'),
(30, 'Staff Parking', 0.00, 'Self-Park H', 1, 'Staff Only, Reserved, Secure', 'available', 'images/parking6.jpg'); 